blank_issues_enabled: false
contact_links:
  - name: Terraform Language or Workflow Feedback and Questions
    url: https://github.com/hashicorp/terraform/issues/new/choose
    about: Terraform Core has its own repository, any language (HCL) or workflow related issues or questions should be directed there.
  - name: Terraform Plugin SDK Feedback
    url: https://github.com/hashicorp/terraform-plugin-sdk/issues/new/choose
    about: The Terraform Plugin SDK has its own repository, any feedback related to the SDK should be directed there.
  - name: ‚ùì Provider Development Questions
    url: https://discuss.hashicorp.com/c/terraform-providers/tf-plugin-sdk
    about: Please ask and answer questions about provider development through the Plugin SDK Community Forum.
